import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from scoring import compute_scores, dimensions
import os

def generate_radar_chart(company_id, df, filename):
    try:
        # Get scores
        row = df[df['Company_ID'] == company_id]
        if row.empty:
            raise ValueError(f"Company ID {company_id} not found.")
            
        scores = [row[f'{dim}_score'].values[0] for dim in dimensions.keys()]
        labels = list(dimensions.keys())

        # Radar chart
        angles = [n / float(len(labels)) * 2 * 3.14159 for n in range(len(labels))]
        scores += scores[:1]
        angles += angles[:1]

        fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(projection='polar'))
        ax.plot(angles, scores, 'o-', linewidth=2, color='#004080')
        ax.fill(angles, scores, alpha=0.25, color='#004080')
        ax.set_xticks(angles[:-1])
        ax.set_xticklabels(labels, size=8)
        ax.set_ylim(0, 100)
        ax.set_title(f'Digital Maturity Profile', y=1.1, weight='bold')
        plt.tight_layout()
        plt.savefig(filename)
        plt.close()
    except Exception as e:
        print(f"Error generating radar chart for {company_id}: {e}")

def create_docx_report(company_id, df_before, df_after):
    try:
        doc = Document()
        
        # Styles
        style = doc.styles['Normal']
        style.font.name = 'Calibri'
        style.font.size = Pt(11)

        # Title
        title = doc.add_heading(f'Digital Maturity Assessment Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Subtitle / Info
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(f"Company ID: {company_id}")
        run.bold = True
        run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

        doc.add_heading('Executive Summary', level=1)
        
        # Data prep
        before_row = df_before[df_before['Company_ID'] == company_id]
        after_row = df_after[df_after['Company_ID'] == company_id]
        overall_before = before_row['Overall_Maturity'].values[0]
        overall_after = after_row['Overall_Maturity'].values[0]
        improvement = overall_after - overall_before

        # Summary Table
        table = doc.add_table(rows=2, cols=3)
        table.style = 'Medium Shading 1 Accent 1'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Initial Maturity'
        hdr_cells[1].text = 'Current Maturity'
        hdr_cells[2].text = 'Improvement'
        
        row_cells = table.rows[1].cells
        row_cells[0].text = f"{overall_before:.1f}%"
        row_cells[1].text = f"{overall_after:.1f}%"
        row_cells[2].text = f"+{improvement:.1f}%"

        doc.add_paragraph("\n")

        # Visuals
        doc.add_heading('Maturity Profile', level=1)
        radar_path = f"images/radar_docx_{company_id}.png"
        
        # Ensure images dir exists
        if not os.path.exists('images'):
            os.makedirs('images')
            
        generate_radar_chart(company_id, df_after, radar_path)
        
        if os.path.exists(radar_path):
            doc.add_picture(radar_path, width=Inches(5.5))
            last_paragraph = doc.paragraphs[-1] 
            last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Detailed Breakdown
        doc.add_page_break()
        doc.add_heading('Dimension Breakdown', level=1)
        
        dim_table = doc.add_table(rows=1, cols=2)
        dim_table.style = 'Light List Accent 1'
        hdr_cells = dim_table.rows[0].cells
        hdr_cells[0].text = 'Dimension'
        hdr_cells[1].text = 'Score (0-100)'
        
        for dim in dimensions.keys():
            score = after_row[f'{dim}_score'].values[0]
            row_cells = dim_table.add_row().cells
            row_cells[0].text = dim
            row_cells[1].text = f"{score:.1f}"

        doc.add_paragraph("\n")

        # Recommendations
        doc.add_heading('Strategic Recommendations', level=1)
        doc.add_paragraph("Based on the assessment, the following actions are recommended:", style='List Bullet')
        doc.add_paragraph("Focus on integrating AI tools to automate repetitive tasks.", style='List Bullet')
        doc.add_paragraph("Strengthen data governance policies to ensure compliance and security.", style='List Bullet')
        doc.add_paragraph("Enhance digital skills training for all employees.", style='List Bullet')

        # Footer
        section = doc.sections[0]
        footer = section.footer
        p = footer.paragraphs[0]
        p.text = "Generated by Digital Maturity Assessment Tool"
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Save
        if not os.path.exists('reports'):
            os.makedirs('reports')
            
        output_filename = f"reports/Report_Company_{company_id}.docx"
        doc.save(output_filename)
        print(f"Generated {output_filename}")

    except Exception as e:
        print(f"Error generating DOCX report for {company_id}: {e}")

def main():
    try:
        # Load data
        if not os.path.exists('data/rawdma_before.xlsx') or not os.path.exists('data/rawdma_after.xlsx'):
             raise FileNotFoundError("Input Excel files not found in data/ directory. Please run data_generator.py first.")

        df_before = pd.read_excel('data/rawdma_before.xlsx')
        df_after = pd.read_excel('data/rawdma_after.xlsx')
        
        df_before = compute_scores(df_before)
        df_after = compute_scores(df_after)

        # Generate for sample companies
        for cid in [1, 2, 3, 4, 5]:
            create_docx_report(cid, df_before, df_after)

    except Exception as e:
        print(f"Error in DOCX report generation: {e}")

if __name__ == "__main__":
    main()
